gsap.from('.picture1', { duration: 3, x: '-100%', ease: 'bounce' })
gsap.from('.aboutpic1', { duration: 3, x: '-100%', ease: 'bounce' })
gsap.from('.picture2', { duration: 4, x: '100%', ease: 'elastic' })
gsap.from('.text', { duration: 3, y: '100%', ease: 'power3' })
gsap.from('.item', { duration: 2, y: '50%', ease: 'power2' })
